version: '3'
services:
  edupal:
    container_name: edupal
    image: ghcr.io/tongque0/edupal/edupal:latest  # 替换为你的后端镜像
    ports:
      - "8080:8080"  # 映射到主机
    environment:
      - GO_ENV=test
    depends_on:
      - mysql
    restart: always

  mysql:
    container_name: mysql
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=gorm
      - MYSQL_USER=gorm
      - MYSQL_PASSWORD=gorm
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
    volumes:
      - mysql_data:/var/lib/mysql

  frontend:
    image: ghcr.io/tongque0/edupal/edupal-frontend:latest  # 替换为你的前端镜像
    ports:
      - "5173:80"
    environment:
      - VUE_APP_BASE_API=/api
    depends_on:
      - edupal
    restart: always

volumes:
  mysql_data:
